import os
import re
import datetime
from collections import defaultdict
from pathlib import Path

WIKI_ROOT = Path(__file__).resolve().parent.parent
PROMPTS_DIR = WIKI_ROOT / "04_Chat_Prompts"
DEVLOGS_DIR = WIKI_ROOT / "03_DevLogs"
PATCHNOTES_FILE = WIKI_ROOT / "00_Dashboard" / "PATCHNOTES.md"

def parse_prompts():
    """Reads all markdown files in PROMPTS_DIR and groups them by date."""
    dates_data = defaultdict(list)

    for filename in os.listdir(PROMPTS_DIR):
        if not filename.endswith(".md"):
            continue

        # Extract date from prefix (YYYY-MM-DD)
        match = re.match(r"^(\d{4}-\d{2}-\d{2})_(.+)\.md$", filename)
        if not match:
            continue

        date_str = match.group(1)

        # Read file to find "Fokus" and the frontmatter title (fallback-summary source)
        filepath = os.path.join(PROMPTS_DIR, filename)
        focus = None
        title = None
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
                # Look for (Fokus: ...) or Fokus: ...
                focus_match = re.search(r'(?i)\(?Fokus:\s*([^)\n]+)\)?', content)
                if focus_match:
                    focus = focus_match.group(1).strip()
                title_match = re.search(r'^title:\s*"([^"]*)"', content, re.MULTILINE)
                if title_match:
                    title = title_match.group(1).strip()
        except Exception:
            pass

        dates_data[date_str].append({
            'filename': filename,
            'focus': focus,
            'title': title
        })

    return dates_data

def parse_devlogs():
    """Reads all DevLog files (03_DevLogs/, generated by generate_vault.py from
    git log) and returns two dicts grouped by date:
      - subjects_data: date -> [subject, ...] deduplicated commit subjects
        (used as fallback source for days without a hand-written summary)
      - filenames_data: date -> [stem, ...] all devlog file stems
        (used for the Verlinkungen (DevLogs) callout in PATCHNOTES.md)
    Both are sorted by filename (i.e. chronologically within the day)."""
    subjects_data = defaultdict(list)   # date -> [subject, ...]
    filenames_data = defaultdict(list)  # date -> [stem, ...]

    if not os.path.isdir(DEVLOGS_DIR):
        return subjects_data, filenames_data

    for filename in sorted(os.listdir(DEVLOGS_DIR)):
        if not filename.endswith(".md") or filename.startswith("_"):
            continue

        # Extract date from filename prefix (YYYY-MM-DD)
        fn_match = re.match(r'^(\d{4}-\d{2}-\d{2})_', filename)
        if not fn_match:
            continue
        date_str = fn_match.group(1)
        stem = filename[:-3]  # without .md
        filenames_data[date_str].append(stem)

        filepath = os.path.join(DEVLOGS_DIR, filename)
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
        except Exception:
            continue

        subject_match = re.search(r'^subject:\s*"([^"]*)"', content, re.MULTILINE)
        if not subject_match:
            continue

        subject = subject_match.group(1).strip()
        if subject and subject not in subjects_data[date_str]:
            subjects_data[date_str].append(subject)

    return subjects_data, filenames_data

def build_auto_fallback(day_prompts, day_subjects):
    """Baut eine automatische Ersatz-Zusammenfassung fuer Tage OHNE
    handgeschriebenen Text in PATCHNOTES.md. Reihenfolge der Quellen:
    1. Echte Commit-Betreffzeilen aus den DevLogs des Tages (day_subjects).
    2. Falls keine DevLogs existieren: Chat-Titel des Tages (day_prompts).
    3. Falls auch das leer ist: alter reiner Platzhalter-Hinweis.
    Wird IMMER deutlich als "automatisch, nicht redigiert" markiert und
    ersetzt niemals bereits vorhandenen handgeschriebenen Text - siehe
    Aufrufstelle in main()."""
    bullets = []
    source = None

    if day_subjects:
        bullets = day_subjects
        source = "DevLogs"
    elif day_prompts:
        titles = []
        for prompt in day_prompts:
            title = prompt.get('title')
            if title and title not in titles:
                titles.append(title)
        if titles:
            bullets = titles
            source = "Chat-Titeln"

    if not bullets:
        return (
            "*Noch keine redaktionelle Zusammenfassung fuer diesen Tag - "
            "bitte in PATCHNOTES.md von Hand ergaenzen (siehe README-Hinweis "
            "im Kopf dieser Datei).*\n"
        )

    lines = [
        f"**Fokus:** *automatisch aus {source} erzeugt \u2014 noch nicht redigiert*\n",
        "### Wichtigste \u00c4nderungen",
    ]
    lines.extend(f"- {bullet}" for bullet in bullets)
    lines.append(
        f"\n*Automatisch generiert aus {source}, keine echte Zusammenfassung \u2014 "
        "bitte durch handgeschriebenen Text ersetzen, siehe Abschnitt 3 im "
        "Dokumentations-Guide (`00_Dashboard/01_Dokumentations_Guide.md`).*\n"
    )
    return '\n'.join(lines)

def parse_existing_patchnotes():
    """Reads existing PATCHNOTES.md and extracts sections per date."""
    if not os.path.exists(PATCHNOTES_FILE):
        return {}
        
    with open(PATCHNOTES_FILE, 'r', encoding='utf-8') as f:
        content = f.read()
        
    # Split by headers like ## 11. August 2026
    date_sections = {}
    current_date = None
    current_content = []
    
    months = {
        "Januar": "01", "Februar": "02", "M\u00e4rz": "03", "April": "04", 
        "Mai": "05", "Juni": "06", "Juli": "07", "August": "08", 
        "September": "09", "Oktober": "10", "November": "11", "Dezember": "12"
    }
    
    for line in content.splitlines():
        # Match dates like "11. August 2026" or "11.08.2026"
        match_str = re.match(r'^##\s+(\d+)\.\s+([A-Za-z\u00e4\u00f6\u00fc\u00c4\u00d6\u00dc]+)\s+(\d{4})', line)
        match_num = re.match(r'^##\s+(\d{2})\.(\d{2})\.(\d{4})', line)
        
        if match_str:
            if current_date:
                date_sections[current_date] = '\n'.join(current_content).strip()
            day, month_name, year = match_str.groups()
            month = months.get(month_name, "01")
            current_date = f"{year}-{month}-{int(day):02d}"
            current_content = []
        elif match_num:
            if current_date:
                date_sections[current_date] = '\n'.join(current_content).strip()
            day, month, year = match_num.groups()
            current_date = f"{year}-{month}-{day}"
            current_content = []
        else:
            if current_date:
                current_content.append(line)
                
    if current_date:
        date_sections[current_date] = '\n'.join(current_content).strip()
        
    return date_sections

def format_german_date(date_str):
    """Converts YYYY-MM-DD to DD.MM.YYYY"""
    try:
        dt = datetime.datetime.strptime(date_str, "%Y-%m-%d")
        return dt.strftime("%d.%m.%Y")
    except:
        return date_str

def main():
    prompts_data = parse_prompts()
    devlog_subjects_data, devlog_filenames_data = parse_devlogs()
    existing_notes = parse_existing_patchnotes()
    
    # Combine all unique dates, sorted descending
    all_dates = sorted(
        set(prompts_data.keys()) | set(existing_notes.keys())
        | set(devlog_subjects_data.keys()) | set(devlog_filenames_data.keys()),
        reverse=True
    )
    
    new_content = [
        "---",
        "tags: [patch-notes, devlogs]",
        "---",
        "",
        "# Patch Notes \u2014 Lemonade",
        "",
        "> *Entwicklungs-History des Spiels, f\u00fcr Spieler aufbereitet*",
        ">",
        "> Jeder Tag wird von Hand zusammengefasst (Devlogs + Chat-Protokolle als Quelle) "
        "statt automatisch aus rohen Commit-Messages generiert. `generate_patchnotes.py` "
        "pflegt nur noch das Skelett (Datums-Header + Verlinkungen) und l\u00e4sst den "
        "redaktionellen Text unangetastet \u2014 siehe Kopfkommentar dort. Tage ohne "
        "handgeschriebenen Text bekommen automatisch einen mit *\u201eautomatisch, noch "
        "nicht redigiert\u201c* markierten Platzhalter aus echten DevLog-Commits (oder, "
        "falls keine existieren, aus Chat-Titeln) statt des alten reinen Hinweistexts."
    ]
    
    for date_str in all_dates:
        new_content.append(f"\n## {format_german_date(date_str)}\n")

        day_prompts = prompts_data.get(date_str, [])
        day_subjects = devlog_subjects_data.get(date_str, [])
        day_devlog_files = devlog_filenames_data.get(date_str, [])

        # WICHTIG: Ist bereits handgeschriebener Text fuer diesen Tag in
        # PATCHNOTES.md vorhanden, wird er 1:1 uebernommen und NIE
        # ueberschrieben - dieses Skript pflegt sonst nur noch das Skelett
        # (Datums-Header + Verlinkungen). Nur wenn fuer den Tag noch GAR
        # kein Text existiert, greift build_auto_fallback() (echte
        # DevLog-Commit-Betreffzeilen, sonst Chat-Titel, sonst der alte
        # reine Platzhalter-Hinweis) - siehe dort.
        #
        # Entscheidend ist der BEREINIGTE Text, nicht der rohe: ein
        # Tagesabschnitt, der nur aus den Verlinkungen-Callouts besteht
        # (kein eigener Fliesstext), gilt NICHT als "hat schon Inhalt" -
        # sonst wuerde der Fallback nie greifen, weil roher Text technisch
        # nicht leer war.
        raw_existing = existing_notes.get(date_str, "")
        cleaned_lines = [
            l for l in raw_existing.splitlines()
            if l.strip() != "---"
            and not l.startswith("[[HOME|Startseite]]")
            and not l.startswith("## Schnellnavigation")
            and not l.startswith("> [!INFO]- Verlinkungen")
            and not (l.startswith("> - [[") and l.rstrip().endswith("]]"))
        ]
        clean_str = '\n'.join(cleaned_lines).strip()
        if clean_str:
            new_content.append(clean_str)
        else:
            new_content.append(build_auto_fallback(day_prompts, day_subjects))

        # Verlinkungen als Obsidian-Callouts (Chat-Protokolle + DevLogs getrennt).
        if day_prompts:
            new_content.append("> [!INFO]- Verlinkungen (Chat-Protokolle)")
            for prompt in day_prompts:
                basename = prompt['filename'][:-3]
                new_content.append(f"> - [[{basename}]]")

        if day_devlog_files:
            new_content.append("> [!INFO]- Verlinkungen (DevLogs)")
            for stem in day_devlog_files:
                new_content.append(f"> - [[{stem}]]")

        new_content.append("\n---")
        
    new_content.append("\n## Schnellnavigation")
    new_content.append("[[HOME|Startseite]] . [[_MOC_Characters|Charaktere]] . [[_MOC_Items|Items]] . [[_MOC_Enemies|Gegner]]")
    
    with open(PATCHNOTES_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(new_content))
        
    print(f"Generated patchnotes for {len(all_dates)} days.")

if __name__ == "__main__":
    main()
